spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eav
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: db/changelog/db.changelog-master.xml


